# site settings
title: badadoo
subtitle: by HTML5 UP
email: paulomoreiraesilva@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/paulomoreiraesilva.github.io
url: https://paulomoreiraesilva.github.io
author:
street_address: 
city: Singapore
state: 
zip_code:
country: The world
phone: +6582319310

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: h
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
